### ISSUE TITLE
Fail at write.xlsx for raw salmon counts 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_tutorial_transcriptome#1]
Hi there, after running the Rmarkdown slave, the execution was halted when running this chunk:

`label: geneCounts (with options)
List of 1
 $ echo: logi FALSE`

`Quitting from lines 246-257 (Nanopore_Transcriptome_Tutorial.Rmd)
Error in .jcheck() :
  Java Exception <no description because toString() failed>.jcall(cell, "V", "setCellValue", value)new("jobjRef", jobj = <pointer: 0x5571a47861f8>, jclass = "java/lang/Throwable")
Calls: <Anonymous> ... .write_block -> mapply -> <Anonymous> -> .jcall -> .jcheck`

I opened the Rmarkdown in Rstudio session and ran each chunk, and again it seems to fail exporting the salmon table out to xlsx.

Is this relating to the memory that java uses? Seems file is too large to export from

This is happening on my MacBook Pro 16GB and on server. 

Is there some upper limit using write.xlsx, the salmon counts is quite large

**Comment by sagrudd** [comment]
Thanks for the feedback @callumparr. I am looking into this at the moment. If you could comment out lines 255 and 256 of the markdown script, the Excel file writing step will be skipped and the analysis should continue. I will change the storage format of the file from xlsx to csv. I'll have an update tested and validated tomorrow. Thanks for your patience here ...

**Comment by sagrudd** [comment]
I have updated the markdown script to write CSV rather than XLSX for the large salmon gene and transcript count tables - this should solve the Excel errors; I am closing this case. Output files in xlsx format are still produced for the tables of genes that satisfy the conditions for differential testing; this is unlikely to be massive data. If an error is thrown by Excel with the fixes, please open a new issue. Please call `git pull` to update the markdown in your working directory

**Comment by callumparr** [comment]
> I have updated the markdown script to write CSV rather than XLSX for the large salmon gene and transcript count tables - this should solve the Excel errors; I am closing this case. Output files in xlsx format are still produced for the tables of genes that satisfy the conditions for differential testing; this is unlikely to be massive data. If an error is thrown by Excel with the fixes, please open a new issue. Please call `git pull` to update the markdown in your working directory

@sagrudd thanks so much, I am just working through it. I will try it first on the sample data sets you provide and then on my own data sets.

**Comment by callumparr** [comment]
@sagrudd just to update. A couple of tables also threw an error when writing out via xlsx format, so had to write out to csv instead. This was the cts_transcript, which just pushed over the limit for writing out. I guess this is system dependent? Amount of memory you permit for rJava? In any case. I guess there is the pipeline_transcriptome_de for working with larger data sets, out of tutorial context.
