### ISSUE TITLE
I cannot get snakemake to run 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_tutorial_transcriptome#4]
Falling at the first hurdle. Is this because some indentation issue? 

`AttributeError in line 6 of /home/minion/pipeline-transcriptome-de/Snakefile:
'Workflow' object has no attribute 'overwrite_configfile'
  File "/home/minion/pipeline-transcriptome-de/Snakefile", line 6, in <module>
`

**Comment by bsipos** [comment]
Try replacing "overwrite_configfile" with "overwrite_configfiles" like this:

```
if not workflow.overwrite_configfiles:
    configfile: "config.yml"
```

The snakemake API changed in the latest version.

**Comment by callumparr** [comment]
> Try replacing "overwrite_configfile" with "overwrite_configfiles" like this:
> 
> ```
> if not workflow.overwrite_configfiles:
>     configfile: "config.yml"
> ```
> 
> The snakemake API changed in the latest version.

it seems to start building the jobs now. will run on test data from transcriptome_tutorial. Sorry I just realized I raised another issue in the wrong repository again.
